### ISSUE TITLE
Remove homepage field in Cargo.toml or replace it with real project homepage

### ISSUE THREAD

**Issue by tesuji** [softprops/recap#12]
Per cargo book: https://doc.rust-lang.org/nightly/cargo/reference/manifest.html#the-homepage-field
https://github.com/softprops/recap/blob/24b023d27de55865eaf6b35c211de3a0647a42d2/recap/Cargo.toml#L11

**Comment by softprops** [comment]
The GitHub repo homepage for the project _is_ the current homepage for the product until it needs something more complicated. I haven't had the need for something more complicated
