### ISSUE TITLE
support option type 

### ISSUE THREAD

**Issue by robatipoor** [softprops/recap#3]
I tried to write something like this 
#### 💻 Basic example
```
use recap::Recap;
use serde::Deserialize;
use std::error::Error;

#[derive(Debug, Deserialize, Recap)]
#[recap(regex = r#"(?x)
    (?P<foo>\d+)
    \s+
    (?P<bar>true|false)
    \s+
    (?P<baz>\S+)
  "#)]
struct LogEntry {
    foo: usize,
    bar: bool,
    baz: Option<String>,
}

fn main() -> Result<(), Box<dyn Error>> {
    let logs = r#"1 true  
    2 false world"#;

    for line in logs.lines() {
        let entry: LogEntry = line.parse()?;
        println!("{:#?}", entry);
    }

    Ok(())
}
```
Error: Custom("No captures resolved in string \'1 true  \'")

**Comment by softprops** [comment]
I think you might be seeing this because the regex doesn't actually match. I'd try making the last capture in the regex optional by following it with a [`?`](https://www.regular-expressions.info/optional.html), i.e `(?P<baz>\S+)?`

**Comment by BurntSushi** [comment]
Hmmm, it looks like it does match? Maybe I mistranslated it though. See: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0e49121c484ca783463028609b7b6076

**Comment by BurntSushi** [comment]
Oh, how silly. Yes. I did mistranslate it. It should be: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d173b62a2504ed421d066df2f3bf1115 ---Which indeed does not match.

**Comment by softprops** [comment]
I'll take a closer look this weekend

**Comment by softprops** [comment]
I added a [quick unit test](https://github.com/softprops/recap/blob/c7093972e49641ba9b71db03943f9292ad86c9f4/recap/src/lib.rs#L147-L170)

**Comment by softprops** [comment]
Closing for now. Have a look at the unit test example and reopen if that isn't what you had in mind
