### ISSUE TITLE
Document an example with enum

### ISSUE THREAD

**Issue by j1elo** [softprops/recap#9]
I'm learning Rust and this library is extremely useful for quick parsing of string data. However I've been stuck trying to parse a value which should be an enum; something like these strings:

```
R ff0000
G 00ff00
B 0000ff
```

My code looks like this:

```
use recap::Recap;
use serde::Deserialize;

#[derive(Deserialize, Recap)]
#[recap(regex = r#"(?P<dir>\w) (?P<code>\w+)"#)]
struct Config {
    type: Color,
    code: String,
}

#[derive(Debug, Deserialize)]
enum Color {
    R,
    G,
    B,
}
```

I have even tried with a `FromStr` implementation, but I'm really blindly trying things because of being too new to the ecosystem and not being able to figure out what direction I should take:

```
impl FromStr for Color {
    type Err = ();
    fn from_str(s: &str) -> Result<Color, ()> {
        match s {
            "R" => Ok(Color::R),
            "G" => Ok(Color::G),
            "B" => Ok(Color::B),
            _ => Err(()),
        }
    }
}
```

What I'd request is to extend the documentation if `recap` can be used for this use case; and otherwise a comment about it, so future beginners don't spend too much time trying to make it work, like me :-)

**Comment by bryangingechen** [comment]
I found an example in the [`envy` tests](https://github.com/softprops/envy/blob/master/src/lib.rs#L365) which was helpful for seeing how to use `enum`s.

Here's a working example of your code; note that I had to rename the `type` field of your `Config` `struct` since Rust doesn't allow a keyword like `type` as a field name:
```rust
use recap::Recap;
use serde::Deserialize;
use std::error::Error;

#[derive(Debug, PartialEq, Deserialize, Recap)]
#[recap(regex = r#"(?P<color>\w) (?P<code>\w+)"#)]
struct Config {
    color: Color,
    code: String,
}

#[derive(Debug, PartialEq, Deserialize)]
enum Color {
    R,
    G,
    B,
}

fn main() -> Result<(), Box<dyn Error>> {
    assert_eq!(
        "R ff0000
G 00ff00
B 0000ff"
            .lines()
            .map(|line| line.parse::<Config>())
            .collect::<Result<Vec<Config>, _>>()?,
        vec![
            Config {
                color: Color::R,
                code: "ff0000".into(),
            },
            Config {
                color: Color::G,
                code: "00ff00".into(),
            },
            Config {
                color: Color::B,
                code: "0000ff".into(),
            },
        ]
    );
    Ok(())
}
```
